### ISSUE TITLE
Idle in make-manhattan step

### ISSUE THREAD

**Issue by phuwanat** [statgen/pheweb#67]
Hello,

After I used pheweb process-assoc-files in my lab's cluster through interactive session, the process is still idle and stay blank for a long time. There is no problem when I tried the same set of inputs in my local PC. Both cases use the latest version of pheweb in 64-bits linux with python 3.5.2 (in the cluster). I believe that this is not enough for troubleshooting the problem. Do you have a verbose or any debugging suggestion on this?

Thanks

**Comment by pjvandehaar** [comment]
Thanks for reporting this.

So, `pheweb phenolist ...` worked fine for making a `pheno-list.json`?

But after running `pheweb process-assoc-files` on your cluster, you don't even see

> ==> Starting `pheweb get-cpras`

?  That's very interesting.

PheWeb doesn't have a verbose mode yet, but I'm sure we can figure something out.  To start with, if you hit control-c to kill `pheweb` while it's frozen, does it die?  If it does, could you give me the error that it prints?  That should tell us what it was trying to do.

**Comment by phuwanat** [comment]
Hello Peter,

Every steps before make-manhattan works very fine. This is the screen when
I terminate the process:

==> Completed in 12430 seconds

==> Starting `pheweb make-manhattan`
number of phenos to process: 175
^CTraceback (most recent call last):
  File "/home/phuwanat/sw/bin/pheweb", line 9, in <module>
    load_entry_point('PheWeb==0.9.15', 'console_scripts', 'pheweb')()
  File
"/home/phuwanat/sw/lib/python3.5/site-packages/pheweb/command_line.py",
line 97, in main
    handlers[subcommand](sys.argv[2:])
  File
"/home/phuwanat/sw/lib/python3.5/site-packages/pheweb/command_line.py",
line 46, in f
    module.run(argv)
  File
"/home/phuwanat/sw/lib/python3.5/site-packages/pheweb/load/process_assoc_files.py",
line 42, in run
    module.run([])
  File
"/home/phuwanat/sw/lib/python3.5/site-packages/pheweb/load/make_manhattan.py",
line 184, in run
    p.map(make_json_file, conversions_to_do)
  File "/home/phuwanat/sw/lib/python3.5/multiprocessing/pool.py", line 260,
in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/phuwanat/sw/lib/python3.5/multiprocessing/pool.py", line 602,
in get
    self.wait(timeout)
  File "/home/phuwanat/sw/lib/python3.5/multiprocessing/pool.py", line 599,
in wait
    self._event.wait(timeout)
  File "/home/phuwanat/sw/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/home/phuwanat/sw/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt

Thanks,
Phuwanat

**Comment by pjvandehaar** [comment]
How did you install PheWeb?  `pip3 install pheweb`, `pip3 install ...github.com/statgen/pheweb...` or `git clone ...; pip3 install .`?

**Comment by phuwanat** [comment]
I used pip3 install ...github.com/statgen/pheweb...

**Comment by phuwanat** [comment]
To be exactly, pip3 install git+https://github.com/statgen/pheweb.git

**Comment by pjvandehaar** [comment]
Alright.  I just created version 0.9.17, in which you can set `debug=True` in your `config.py` or you can run `pheweb debug process-assoc-files` or `pheweb debug make-manhattan` or whatever you want.  So far that only changes behavior in making the Manhattan plot.  `pip3 install git+https://github.com/statgen/pheweb.git` should get it for you.

**Comment by phuwanat** [comment]
I have been waiting for the file to processed but it was still stuck. This is the output from Pheweb instance:


...

==> Starting `pheweb download-rsids`
dbsnp is at '/home/repsa/.pheweb/cache/rsids-147.vcf.gz'
==> Completed in 0 seconds

==> Starting `pheweb download-genes`
gencode is at '/home/repsa/.pheweb/cache/genes.bed'
==> Completed in 0 seconds

==> Starting `pheweb make-gene-aliases-trie`
gene aliases are at '/home/repsa/.pheweb/cache/gene_aliases.marisa_trie'
==> Completed in 0 seconds

==> Starting `pheweb add-rsids`
==> Completed in 1136 seconds

==> Starting `pheweb add-genes`
==> Completed in 3 seconds

==> Starting `pheweb make-tries`
done loading.
done with cpra->rsids trie at /home/repsa/pheweb_test/sites/cpra_to_rsids_trie.marisa
done with rsid->cpra trie at /home/repsa/pheweb_test/sites/rsid_to_cpra_trie.marisa
==> Completed in 0 seconds

==> Starting `pheweb standardize-phenos`
number of phenos: 1
number of phenos to process: 1
2017-04-05 22:04:41.894687      wbcChr11 -> /home/repsa/pheweb_test/augmented_pheno/wbcChr11
==> Completed in 1 seconds

==> Starting `pheweb make-manhattan`
number of phenos to process: 1
2017-04-05 22:04:41.966672      /home/repsa/pheweb_test/augmented_pheno/wbcChr11 -> /home/repsa/pheweb_test/manhattan/wbcChr11.json (START)
2017-04-05 22:04:41.967446      OPENED /home/repsa/pheweb_test/augmented_pheno/wbcChr11
2017-04-05 22:04:41.967523      OPENED VARIANTS

And this is a corresponding process (python3):
% ps -ejH | grep python3
18154 18154 16763 pts/3    23:48:13             python3

Thanks,

**Comment by pjvandehaar** [comment]
Could you update to the latest PheWeb and run `pheweb debug make-manhattan`? or `pheweb debug process-assoc-files` if you prefer?

**Comment by phuwanat** [comment]
This is the result from `debug process-assoc-files` :
```
==> Starting `pheweb add-rsids`
==> Completed in 1468 seconds

==> Starting `pheweb add-genes`
==> Completed in 3 seconds

==> Starting `pheweb make-tries`
done loading.
done with cpra->rsids trie at /home/phuwanat/pheweb_test_Apr21/sites/cpra_to_rsids_trie.marisa
done with rsid->cpra trie at /home/phuwanat/pheweb_test_Apr21/sites/rsid_to_cpra_trie.marisa
==> Completed in 0 seconds

==> Starting `pheweb standardize-phenos`
number of phenos: 1
number of phenos to process: 1
2017-04-21 17:32:46.017304      wbcChr11 -> /home/phuwanat/pheweb_test_Apr21/augmented_pheno/wbcChr11
==> Completed in 1 seconds

==> Starting `pheweb make-manhattan`
number of phenos to process: 1
2017-04-21 17:32:46.403033      /home/phuwanat/pheweb_test_Apr21/augmented_pheno/wbcChr11 -> /home/phuwanat/pheweb_test_Apr21/manhattan/wbcChr11.json (START)
2017-04-21 17:32:46.403902      OPENED /home/phuwanat/pheweb_test_Apr21/augmented_pheno/wbcChr11
2017-04-21 17:32:46.403990      OPENED VARIANTS
```

The python3 process is still running.
![screenshot from 2017-04-22 11-38-47](https://cloud.githubusercontent.com/assets/14257398/25305817/5304d37e-2750-11e7-9865-6a19610f3e81.png)

**Comment by pjvandehaar** [comment]
Hi, I still don't understand what's going wrong, but PheWeb has changed a lot in the `dev` branch, so maybe if you `pip3 install git+https://github.com/statgen/pheweb.git@dev` that will work.

**Comment by phuwanat** [comment]
I have just tried the latest dev version. The same problem still persisted but it work pretty well with my Ubuntu PC.

```
% pheweb debug process-assoc-files 
==> Starting `pheweb phenolist verify`
The 5 phenotypes in '/home/phuwanat/test/pheno-list.json' look good.
==> Completed in 0 seconds

==> Starting `pheweb parse-input-files`
number of phenos: 5
number of phenos to process: 0
Parsing input files: 0it [00:00, ?it/s]
==> Completed in 0 seconds

==> Starting `pheweb sites`
The list of sites is up-to-date!
==> Completed in 0 seconds

==> Starting `pheweb download-rsids`
dbsnp is at '/home/phuwanat/.pheweb/cache/rsids-150.vcf.gz'
==> Completed in 0 seconds

==> Starting `pheweb download-genes`
gencode is at '/home/phuwanat/.pheweb/cache/genes-v25.bed'
==> Completed in 0 seconds

==> Starting `pheweb make-gene-aliases-trie`
gene aliases are at '/home/phuwanat/.pheweb/cache/gene_aliases.marisa_trie'
==> Completed in 0 seconds

==> Starting `pheweb add-rsids`
rsid annotation is up-to-date!
==> Completed in 0 seconds

==> Starting `pheweb add-genes`
gene annotation is up-to-date!
==> Completed in 0 seconds

==> Starting `pheweb make-tries`
tries are up-to-date!
==> Completed in 0 seconds

==> Starting `pheweb augment-phenos`
number of phenos: 5
number of phenos to process: 0
Annotating phenos: 0it [00:00, ?it/s]
==> Completed in 0 seconds

==> Starting `pheweb manhattan`
number of phenos to process: 5
Precalculating Manhattan Plots:   0%|                                                                                                 | 0/5 [00:00<?, ?it/s]
```

**Comment by pjvandehaar** [comment]
Sorry about such a confusing bug, thanks for continuing to try to figure it out.

Could you try `pheweb qq` and `pheweb bgzip-phenos` and confirm that they have the same bug?

I'll install better KeyboardInterrupt handling, so that it'll print what line the worker processes are on when they hang.

**Comment by pjvandehaar** [comment]
I finally solved this in `0cdf5`.
